server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false  # El servidor no se auto-registra
    fetch-registry: true # No necesita buscar otros servidores
    service-url:
      defaultZone: http://localhost:8761/eureka




